[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer"]

[functions."api/result/[sessionId]"]
  timeout = 30

[functions."api/download/[sessionId]"]
  timeout = 10
