import React from 'react'

interface PlainTextDocument {
  text: string
  metadata?: {
    name?: string
    dob?: string
    city?: string
    companyName?: string
    [key: string]: string | undefined
  }
}

interface GenericTemplateProps {
  document: PlainTextDocument
  brand?: {
    organizationName: string
    logo?: string
    color?: string
  }
  sanitizedInputs?: {
    org_sanitized?: boolean
    sanitized_reason?: string
    [key: string]: any
  }
  serviceType?: string
}

export default function GenericTemplate({ document, brand, sanitizedInputs, serviceType = 'Document' }: GenericTemplateProps) {
  const getServiceColor = () => {
    switch (serviceType) {
      case 'criminal-record':
      case 'universal-credit':
        return '#0a2540' // Government blue
      case 'payslip':
      case 'credit-score':
        return '#123f2c' // Finance green
      case 'college-degree':
      case 'school-behaviour':
        return '#703030' // Education maroon
      default:
        return '#0a2540'
    }
  }

  const getServiceTitle = () => {
    switch (serviceType) {
      case 'criminal-record':
        return 'Police National Computer Record (Fictional)'
      case 'universal-credit':
        return 'Universal Credit Assessment Report (Fictional)'
      case 'credit-score':
        return 'Credit Score Report (Fictional)'
      case 'job-rejection':
        return 'Application Outcome Letter (Fictional)'
      case 'rent-reference':
        return 'Landlord Reference Letter (Fictional)'
      case 'school-behaviour':
        return 'School Behaviour Record Reprint (Fictional)'
      case 'college-degree':
        return 'University Degree Certificate (Fictional)'
      default:
        return 'Document (Fictional)'
    }
  }

  const color = getServiceColor()
  const title = getServiceTitle()

  return (
    <div className="generic-document" style={{
      fontFamily: 'Arial, sans-serif',
      fontSize: '12px',
      lineHeight: '1.4',
      color: '#000',
      backgroundColor: '#ffffff',
      padding: '30px',
      minHeight: '100vh',
      position: 'relative'
    }}>
      {/* Watermark */}
      <div className="watermark" style={{
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-30deg)',
        fontSize: '48px',
        fontWeight: 'bold',
        color: 'rgba(0, 0, 0, 0.06)',
        zIndex: 1,
        pointerEvents: 'none',
        userSelect: 'none'
      }}>
        INTERNET STREETS ENTERTAINMENT
      </div>

      {/* Header */}
      <div className="header" style={{
        borderBottom: `2px solid ${color}`,
        paddingBottom: '15px',
        marginBottom: '25px',
        position: 'relative',
        zIndex: 2
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h1 style={{
              fontSize: '20px',
              fontWeight: 'bold',
              color: color,
              margin: '0 0 5px 0',
              fontFamily: 'Arial, sans-serif'
            }}>
              {title}
            </h1>
            <div style={{ fontSize: '10px', color: '#666', marginTop: '3px' }}>
              Document ID: {serviceType.toUpperCase()}-{Math.random().toString(36).substr(2, 8).toUpperCase()} • Generated by Internet Streets
            </div>
          </div>
          
          {/* Organization Logo/Seal */}
          <div style={{
            width: '70px',
            height: '70px',
            border: `2px solid ${color}`,
            borderRadius: '8px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f8f9fa',
            boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
          }}>
            <div style={{ fontSize: '8px', fontWeight: 'bold', color: color, textAlign: 'center' }}>
              {brand?.organizationName || 'ORGANIZATION'}
            </div>
            <div style={{ fontSize: '6px', color: '#666', marginTop: '2px' }}>
              OFFICIAL
            </div>
          </div>
        </div>
      </div>

      {/* Document Content */}
      <div className="document-content" style={{
        position: 'relative',
        zIndex: 2,
        whiteSpace: 'pre-wrap',
        fontFamily: 'Arial, sans-serif',
        fontSize: '11px',
        lineHeight: '1.5'
      }}>
        {document.text}
      </div>

      {/* Footer */}
      <div style={{
        position: 'fixed',
        bottom: '20px',
        left: '50%',
        transform: 'translateX(-50%)',
        fontSize: '9px',
        color: '#666',
        textAlign: 'center',
        zIndex: 2
      }}>
        Internet Streets Entertainment – Not a Real Document
      </div>

      {/* Signature placeholder */}
      <div style={{
        position: 'absolute',
        bottom: '60px',
        right: '30px',
        fontSize: '10px',
        color: '#666',
        zIndex: 2
      }}>
        <div style={{ borderBottom: '1px solid #000', width: '120px', marginBottom: '5px' }}></div>
        <div>Authorized Signature</div>
      </div>
    </div>
  )
}
