import React from 'react'

interface PlainTextDocument {
  text: string
  metadata?: {
    name?: string
    dob?: string
    city?: string
    companyName?: string
    [key: string]: string | undefined
  }
}

interface JobRejectionTemplateProps {
  document: PlainTextDocument
  brand?: {
    text: string
    svg?: string
    colors?: any
  }
  sanitizedInputs?: {
    org_sanitized?: boolean
    sanitized_reason?: string
    [key: string]: any
  }
}

export default function JobRejectionTemplate({ document, brand, sanitizedInputs }: JobRejectionTemplateProps) {
  return (
    <div className="job-rejection-document" style={{
      fontFamily: 'Arial, sans-serif',
      fontSize: '12px',
      lineHeight: '1.4',
      color: '#000',
      backgroundColor: '#ffffff',
      padding: '30px',
      minHeight: '100vh',
      position: 'relative'
    }}>
      {/* Watermark */}
      <div className="watermark" style={{
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-30deg)',
        fontSize: '48px',
        fontWeight: 'bold',
        color: 'rgba(0, 0, 0, 0.06)',
        zIndex: 1,
        pointerEvents: 'none',
        userSelect: 'none'
      }}>
        INTERNET STREETS ENTERTAINMENT
      </div>

      {/* Header */}
      <div className="header" style={{
        borderBottom: '2px solid #123f2c',
        paddingBottom: '15px',
        marginBottom: '25px',
        position: 'relative',
        zIndex: 2
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h1 style={{
              fontSize: '20px',
              fontWeight: 'bold',
              color: '#123f2c',
              margin: '0 0 5px 0',
              fontFamily: 'Arial, sans-serif'
            }}>
              Application Outcome Letter (Fictional)
            </h1>
            <div style={{ fontSize: '10px', color: '#666', marginTop: '3px' }}>
              Letter ID: REJECT-{Math.random().toString(36).substr(2, 8).toUpperCase()} • Generated by Internet Streets
            </div>
          </div>
          
          {/* Company Logo/Seal */}
          <div style={{
            width: '70px',
            height: '70px',
            border: '2px solid #123f2c',
            borderRadius: '8px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f8f9fa',
            boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
          }}>
            <div style={{ fontSize: '8px', fontWeight: 'bold', color: '#123f2c', textAlign: 'center' }}>
              {brand?.text || 'COMPANY'}
            </div>
            <div style={{ fontSize: '6px', color: '#666', marginTop: '2px' }}>
              OFFICIAL
            </div>
          </div>
        </div>
      </div>

      {/* Document Content */}
      <div className="document-content" style={{
        position: 'relative',
        zIndex: 2,
        whiteSpace: 'pre-wrap',
        fontFamily: 'Arial, sans-serif',
        fontSize: '11px',
        lineHeight: '1.5'
      }}>
        {document.text}
      </div>

      {/* Footer */}
      <div style={{
        position: 'fixed',
        bottom: '20px',
        left: '50%',
        transform: 'translateX(-50%)',
        fontSize: '9px',
        color: '#666',
        textAlign: 'center',
        zIndex: 2
      }}>
        Internet Streets Entertainment – Not a Real Document
      </div>

      {/* Signature placeholder */}
      <div style={{
        position: 'absolute',
        bottom: '60px',
        right: '30px',
        fontSize: '10px',
        color: '#666',
        zIndex: 2
      }}>
        <div style={{ borderBottom: '1px solid #000', width: '120px', marginBottom: '5px' }}></div>
        <div>HR Manager Signature</div>
      </div>
    </div>
  )
}
