import React from 'react'

interface PlainTextDocument {
  text: string
  metadata?: {
    name?: string
    dob?: string
    city?: string
    companyName?: string
    [key: string]: string | undefined
  }
}

interface NSATemplateProps {
  document: PlainTextDocument
  brand?: {
    organizationName: string
    logo?: string
    color?: string
  }
  sanitizedInputs?: {
    org_sanitized?: boolean
    sanitized_reason?: string
    [key: string]: any
  }
}

export default function NSATemplate({ document, brand, sanitizedInputs }: NSATemplateProps) {
  return (
    <div className="nsa-document" style={{
      fontFamily: 'Georgia, serif',
      fontSize: '12px',
      lineHeight: '1.4',
      color: '#000',
      backgroundColor: '#fafafa',
      padding: '40px',
      minHeight: '100vh',
      position: 'relative'
    }}>
      {/* Watermark */}
      <div className="watermark" style={{
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-30deg)',
        fontSize: '48px',
        fontWeight: 'bold',
        color: 'rgba(0, 0, 0, 0.06)',
        zIndex: 1,
        pointerEvents: 'none',
        userSelect: 'none'
      }}>
        INTERNET STREETS ENTERTAINMENT
      </div>

      {/* Header */}
      <div className="header" style={{
        borderBottom: '3px solid #0a2540',
        paddingBottom: '20px',
        marginBottom: '30px',
        position: 'relative',
        zIndex: 2
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h1 style={{
              fontSize: '24px',
              fontWeight: 'bold',
              color: '#0a2540',
              margin: '0 0 10px 0',
              fontFamily: 'Georgia, serif'
            }}>
              NSA Surveillance Activity Log (Fictional)
            </h1>
            <div style={{ fontSize: '10px', color: '#666', marginTop: '5px' }}>
              Document ID: NSA-{Math.random().toString(36).substr(2, 8).toUpperCase()} • Generated by Internet Streets
            </div>
          </div>
          
          {/* Faux Seal */}
          <div style={{
            width: '80px',
            height: '80px',
            border: '3px solid #0a2540',
            borderRadius: '50%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#f8f9fa',
            boxShadow: 'inset 0 0 10px rgba(0,0,0,0.1)'
          }}>
            <div style={{ fontSize: '8px', fontWeight: 'bold', color: '#0a2540', textAlign: 'center' }}>
              NATIONAL SECURITY<br/>AGENCY
            </div>
            <div style={{ fontSize: '6px', color: '#666', marginTop: '2px' }}>
              OFFICIAL
            </div>
          </div>
        </div>
      </div>

      {/* Classification Stamp */}
      <div style={{
        position: 'absolute',
        top: '20px',
        right: '20px',
        transform: 'rotate(-30deg)',
        fontSize: '12px',
        fontWeight: 'bold',
        color: '#b80f2a',
        backgroundColor: 'rgba(184, 15, 42, 0.1)',
        padding: '5px 10px',
        border: '2px solid #b80f2a',
        borderRadius: '3px',
        zIndex: 2
      }}>
        TOP SECRET
      </div>

      {/* Document Content */}
      <div className="document-content" style={{
        position: 'relative',
        zIndex: 2,
        whiteSpace: 'pre-wrap',
        fontFamily: 'Roboto, Arial, sans-serif',
        fontSize: '11px',
        lineHeight: '1.5'
      }}>
        {document.text}
      </div>

      {/* Footer */}
      <div style={{
        position: 'fixed',
        bottom: '20px',
        left: '50%',
        transform: 'translateX(-50%)',
        fontSize: '9px',
        color: '#666',
        textAlign: 'center',
        zIndex: 2
      }}>
        Internet Streets Entertainment – Not a Real Document
      </div>

      {/* QR Code placeholder */}
      <div style={{
        position: 'absolute',
        bottom: '20px',
        right: '20px',
        width: '60px',
        height: '60px',
        border: '1px solid #ccc',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '8px',
        color: '#999',
        zIndex: 2
      }}>
        QR CODE
      </div>
    </div>
  )
}
