import { createBaseHTML } from '../lib/render'

export default function PayslipTemplate(json: any): string {
  const content = `
    <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="font-size: 28px; font-weight: bold; color: #333; margin-bottom: 10px;">
          PAYSLIP
        </h1>
        <div style="border-bottom: 2px solid #333; width: 100px; margin: 0 auto;"></div>
      </div>

      <!-- Employer & Employee Info -->
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 25px;">
        <div style="background: #f8f9fa; padding: 15px; border: 1px solid #ddd;">
          <h3 style="font-size: 14px; color: #333; margin-bottom: 10px;">EMPLOYER</h3>
          <p style="font-weight: bold; font-size: 16px;">${json.employer?.company || 'N/A'}</p>
        </div>
        <div style="background: #f8f9fa; padding: 15px; border: 1px solid #ddd;">
          <h3 style="font-size: 14px; color: #333; margin-bottom: 10px;">EMPLOYEE</h3>
          <p style="font-weight: bold; font-size: 16px;">${json.employee?.name || 'N/A'}</p>
          <p style="font-size: 14px; color: #666;">${json.employee?.job_title || 'N/A'}</p>
        </div>
      </div>

      <!-- Pay Period -->
      <div style="background: #e3f2fd; padding: 15px; margin-bottom: 25px; border-left: 4px solid #2196f3;">
        <h3 style="font-size: 14px; color: #1976d2; margin-bottom: 8px;">PAY PERIOD</h3>
        <p style="font-weight: bold;">Pay Date: ${json.pay_period?.pay_date || 'N/A'}</p>
      </div>

      <!-- Amounts Table -->
      <div style="margin-bottom: 25px;">
        <h3 style="font-size: 16px; color: #333; margin-bottom: 15px;">PAYMENT DETAILS</h3>
        <table style="width: 100%; border-collapse: collapse; border: 1px solid #ddd;">
          <tbody>
            <tr style="background: #f8f9fa;">
              <td style="border: 1px solid #ddd; padding: 12px; font-weight: bold;">Gross Pay</td>
              <td style="border: 1px solid #ddd; padding: 12px; text-align: right; font-weight: bold;">
                £${json.amounts?.gross_pay_gbp || '0.00'}
              </td>
            </tr>
            <tr>
              <td style="border: 1px solid #ddd; padding: 12px;">Income Tax (${(json.amounts?.tax_rate || 0) * 100}%)</td>
              <td style="border: 1px solid #ddd; padding: 12px; text-align: right;">
                £${json.amounts?.tax_amount_gbp || '0.00'}
              </td>
            </tr>
            <tr style="background: #f8f9fa;">
              <td style="border: 1px solid #ddd; padding: 12px;">National Insurance (${(json.amounts?.ni_rate || 0) * 100}%)</td>
              <td style="border: 1px solid #ddd; padding: 12px; text-align: right;">
                £${json.amounts?.ni_amount_gbp || '0.00'}
              </td>
            </tr>
            <tr style="background: #e8f5e8; border-top: 2px solid #4caf50;">
              <td style="border: 1px solid #ddd; padding: 12px; font-weight: bold; font-size: 16px;">NET PAY</td>
              <td style="border: 1px solid #ddd; padding: 12px; text-align: right; font-weight: bold; font-size: 16px; color: #2e7d32;">
                £${json.amounts?.net_pay_gbp || '0.00'}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- References -->
      <div style="background: #f8f9fa; padding: 15px; margin-bottom: 25px; border: 1px solid #ddd;">
        <h3 style="font-size: 14px; color: #333; margin-bottom: 10px;">REFERENCES</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
          <div><strong>Employee No:</strong> ${json.references?.employee_no || 'N/A'}</div>
          <div><strong>Slip No:</strong> ${json.references?.slip_no || 'N/A'}</div>
        </div>
      </div>

      <!-- Footer -->
      <div style="text-align: center; margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd;">
        <p style="font-size: 12px; color: #666;">
          Generated by Internet Streets - The AI Black Market
        </p>
      </div>
    </div>
  `

  return createBaseHTML(content, 'Payslip')
}
